matchHikingTrail<-function(
  gpsFile,
  networkFile,
  outFile=tempfile(),
  sigmaZ=10.0,
  selection=50.0,
  beta=6.0,
  distanceLimit=2000.0)
{
  command=paste("java",
                "mapmatcher.MatchHikingTrail",
                gpsFile,
                networkFile,
                outFile,
                sigmaZ=10.0,
                selection=50.0,
                beta=6.0,
                distanceLimit)
  system(command)
  read.table(outFile,header=TRUE)
}
